### PR TITLE
Try using vips

### PR DESCRIPTION
**Pull request by n0vad3v**
Recommended by @BennyThink , this PR tries to rewrite encoder part to encode with `github.com/davidbyttow/govips`, will introduce the following changes:
* Use `github.com/davidbyttow/govips` for encode WebP and AVIF images
* Quality set 100 will use Lossless encode mode
* `invalid checksum` problem described in https://github.com/webp-sh/webp_server_go/issues/137 has been solved, it can generate webp image type with the following warnings:
```
2023/05/08 12:49:47 [VIPS.warning] eXIf: CRC error
2023/05/08 12:49:47 [VIPS.warning] eXIf: CRC error
2023/05/08 12:49:47 [VIPS.warning] eXIf: CRC error
2023/05/08 12:49:47 [VIPS.warning] eXIf: CRC error
2023/05/08 12:49:47 [VIPS.warning] eXIf: CRC error
2023/05/08 12:49:47 [VIPS.warning] eXIf: CRC error
time="2023-05-08 12:49:47" level=info msg="WebP@%!f(int=80)%: pics/invalid.png->exhaust/invalid.png.1683549792.webp 199961->27574 13.79% deflated" func="[194:main.convertLog()]"
time="2023-05-08 12:49:48" level=info msg="AVIF@%!f(int=80)%: pics/invalid.png->exhaust/invalid.png.1683549792.avif 199961->58324 29.17% deflated" func="[194:main.convertLog()]"
time="2023-05-08 12:49:48" level=debug msg="The compression rate is 199961/27574=0.14" func="[183:main.getCompressionRate()]"
```
* `missing 0xff00 sequence` problem in https://github.com/webp-sh/webp_server_go/issues/137 remains unsolved

We need more tests on this before consider merging this PR.

### CODE REVIEW

**Review by BennyThink — APPROVED** [review]

**Comment by n0vad3v** [comment]
We need to notice that using vips will produce a huge docker image compared to before.
```
REPOSITORY                                  TAG                  IMAGE ID       CREATED         SIZE
webpsh/webp-server-go                       latest               d453cc0125a2   9 minutes ago   980MB
webpsh/webps                                latest               773481d82e58   6 weeks ago      93.6MB
```

**Comment by n0vad3v** [comment]
Now the image is a little bit smaller:
```
REPOSITORY                                  TAG                  IMAGE ID       CREATED          SIZE
webpsh/webp-server-go                       latest               39a4fb329c32   45 minutes ago   532MB

```

**Comment by n0vad3v** [comment]
Even smaller, inspired by @BennyThink 
```
REPOSITORY                                  TAG                  IMAGE ID       CREATED         SIZE
webpsh/webp-server-go                       latest               b6ee9d80f85a   2 minutes ago   223MB
```

**Comment by n0vad3v** [comment]
Benchmark result:

github.com/davidbyttow/govips
```
Prefetching... 100% |███████████████████████████████████████████████████████| (219/219, 9 it/s)         
Prefetch completeY(^_^)Y in 23.350871663s
```

github.com/chai2010/webp
```
Prefetching... 100% |█████████████████████████████████████████████████████| (219/219, 2 it/s)           
Prefetch completeY(^_^)Y in 1m49.868976512s
```

**Pull request merged**
