### PR TITLE
Multiple backends support

### PR DESCRIPTION
**Pull request by bugfest**
Implements #206 

- Support multiple backends in proxy mode
- Enable proxy mode in new config option: `IMG_MAP` as per #217
- Fixes avif matchers (`h2non/filetype` upgraded)
- Goups remote-raw and exhaust assets in separate directories

### CODE REVIEW

**Comment by BennyThink** [comment]
Hash algorithm: we're using it for identification, not cryptography, so choose the fastest algorithm https://cyan4973.github.io/xxHash/

**Comment by bugfest** [comment]
@n0vad3v, @BennyThink this PR is ready for review

**Comment by BennyThink** [comment]
Great! I will take a look during weekends!

**Comment by n0vad3v** [comment]
Emmm, I've tried this branch with configuration as below, with some images under `pics` and `pics2` (`pics3` does not exist).

```
{
  "HOST": "127.0.0.1",
  "PORT": "3333",
  "IMG_PATH": "./pics",
  "EXHAUST_PATH": "./exhaust",
  "IMG_MAP": {
    "/2": "./pics2",
    "/3": "./pics3",
    "www.example.com": "http://origin.example.com:8000",
    "http://www.example.com": "https://docs.webp.sh"
  },
  "ALLOWED_TYPES": ["jpg","png","jpeg"],
  "ENABLE_AVIF": false,
  "ENABLE_EXTRA_PARAMS": false
}

```

1. Tried to visit: `http://localhost:3333/DSC05953.jpg`, works fine
2. Tried to visit: `http://localhost:3333/2/Unknown.jpg` where `Unknown.jpg` is an image under `pics2` directory, returns `image not found`
3. Tried to visit: `http://localhost:3333/www.example.com/`, returns `File extension not allowed! www.example.com`
4. Tried to visit: `http://localhost:3333/www.example.com/1.jpg`, returns `image not found`

Not sure if I've done something wrong 🤔 

BTW, should we delete the metadata JSON file if the image doesn't exist, inside the function below:

```go
	// Check the original image for existence,
	if !helper.ImageExists(rawImageAbs) {
		msg := "image not found"
		_ = c.Send([]byte(msg))
		log.Warn(msg)
		_ = c.SendStatus(404)
		// DELETE JSON HERE?
		return nil
	}
```

**Comment by bugfest** [comment]
Thanks @n0vad3v, going to add test cases for those and fix them accordingly

**Comment by bugfest** [comment]
Hi @n0vad3v,

> Emmm, I've tried this branch with configuration as below, with some images under `pics` and `pics2` (`pics3` does not exist).
> 
> ```
> {
>   "HOST": "127.0.0.1",
>   "PORT": "3333",
>   "IMG_PATH": "./pics",
>   "EXHAUST_PATH": "./exhaust",
>   "IMG_MAP": {
>     "/2": "./pics2",
>     "/3": "./pics3",
>     "www.example.com": "http://origin.example.com:8000",
>     "http://www.example.com": "https://docs.webp.sh"
>   },
>   "ALLOWED_TYPES": ["jpg","png","jpeg"],
>   "ENABLE_AVIF": false,
>   "ENABLE_EXTRA_PARAMS": false
> }
> ```
> 
>     1. Tried to visit: `http://localhost:3333/DSC05953.jpg`, works fine
> 
>     2. Tried to visit: `http://localhost:3333/2/Unknown.jpg` where `Unknown.jpg` is an image under `pics2` directory, returns `image not found`
> 
>     3. Tried to visit: `http://localhost:3333/www.example.com/`, returns `File extension not allowed! www.example.com`
> 
>     4. Tried to visit: `http://localhost:3333/www.example.com/1.jpg`, returns `image not found`

I forgot to implement the path mapping case :_) 

I implemented it and added more tess to cover these scenarios. The most important decision is assumming keys not starting with "/" or "http://" or "https://" won't be applied. I haven't showed any warning as I'm not parsing that config piece on boot (should we?); right now invalid entries are just skipped. 

> BTW, should we delete the metadata JSON file if the image doesn't exist, inside the function below:
> 
> ```go
> 	// Check the original image for existence,
> 	if !helper.ImageExists(rawImageAbs) {
> 		msg := "image not found"
> 		_ = c.Send([]byte(msg))
> 		log.Warn(msg)
> 		_ = c.SendStatus(404)
> 		// DELETE JSON HERE?
> 		return nil
> 	}
> ```

Yeah, probably it's a good idea. Is something we need to do in this PR?

**Comment by n0vad3v** [comment]
Nice!(Sorry I've missed your reply and update for a long time)

> Is something we need to do in this PR?
No, we will update this in another PR.

**Review by n0vad3v — APPROVED** [review]

**Comment by bugfest** [comment]
> Nice and thank you! ❤️ (Sorry I've missed your reply and update for a long time)
> 
> > I haven't showed any warning as I'm not parsing that config piece on boot (should we?);
> 
> Probably adding a warining there will be better.

Ok, will do. I'll parse the config at boot to show these warnings once if applicable.

> I'm still using `config.json` with content as below:
> 
> ```json
> {
>   "HOST": "127.0.0.1",
>   "PORT": "3333",
>   "IMG_PATH": "",
>   "EXHAUST_PATH": "./exhaust",
>   "IMG_MAP": {
>     "/2": "./pics2",
>     "/3": "./pics3",
>     "www.example.com": "http://origin.example.com:8000",
>     "http://www.example.com": "https://docs.webp.sh"
>   },
>   "ALLOWED_TYPES": ["jpg","png","jpeg"],
>   "ENABLE_AVIF": false,
>   "ENABLE_EXTRA_PARAMS": false
> }
> ```
> 
> And found that if `IMG_PATH` is set to `./pics`, then `http://localhost:3333/2/Unknown.jpg` will try to use image at `./pics/pic2/Unknown.jpg`, but if `IMG_PATH` is set to empty, images will be served from `./pic2/Unknown.jpg`.

I assummed all paths are relative to IMG_PATH, but I guess we can make then relative to the CWD of the process - is it what you expect @n0vad3v?

**Comment by n0vad3v** [comment]
> is it what you expect

Yes, because there are no documents to refer, my first reaction is that the addresses in each IMG_MAP are relative paths starting from the CWD.(However if `IMG_PATH` is set to empty, it indeed works as I expected)

Perhaps it would be better for each one to start from the CWD (Current Working Directory)?
 (It's unlikely that someone would need to serve multiple paths simultaneously, as all those paths would be under `IMG_PATH` anyway.) 

However, I believe both approaches are acceptable as long as they are clearly documented.

**Comment by bugfest** [comment]
Hi @n0vad3v, I've added the patch for the CWD and the IMG_MAP parser on start. Please review.

**Comment by n0vad3v** [comment]
Nice! I'm merging this PR.

**Pull request merged**
